# Generated by Django 5.0.7 on 2024-08-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0003_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
